name: OpenLearnXML2
on:
  issues:
    types: [opened, reopened]
jobs:
  openlearn-files-issue:
    if: startsWith(github.event.issue.title, 'Fetch https://www.open.edu/openlearn') && (github.event.issue.author_association=='COLLABORATOR' || github.event.issue.author_association=='MEMBER' || github.event.issue.author_association=='OWNER') && github.event.issue.user.login==github.actor
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
 
  #  - name: Show context
  #    env:
  #      GITHUB_CONTEXT: ${{ toJson(github) }}
  #    run: echo "$GITHUB_CONTEXT"

    - name: Install dependencies
      run: python -m pip install --upgrade git+https://github.com/innovationOUtside/open-ouxml-tools.git
      
    - name: Copy Repository Contents
      uses: actions/checkout@v2


    - name: parse issue
      run: |
        issue="${{github.event.issue.body}}"
        echo "Issue: $issue"
        echo ::set-env name=url::"$(cut -d' ' -f2 <<<"$issue")"
        echo ::set-env name=outdir::"$(cut -d' ' -f3 <<<"$issue")"
        echo ::set-env name=issue::$issue
    - name: grab ouxml
      run: |
        ouxml_grab $url
 
    - name: convert to md
      run: |
        ouxml2md --dbname openlearn_oer.db --outdir "$outdir"
        
    - name: git add and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "$outdir"
        git add openlearn_oer.db
        git commit -m"Add content to $outdir from $url" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
