name: OpenLearnXML
on:
  push

jobs:
  openlearn-files:
    if: startsWith(github.event.commits[0].message, 'Fetch https://www.open.edu/openlearn')
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
 
    - name: Install dependencies
      run: python -m pip install --upgrade git+https://github.com/innovationOUtside/open-ouxml-tools.git
      
    - name: Copy Repository Contents
      uses: actions/checkout@v2


    - name: parse commit message
      run: |
        commitmsg="$(git log --format=%B -n 1 ${{ github.event.after }})"
        echo ::set-env name=url::"$(cut -d' ' -f2 <<<"$commitmsg")"
        echo ::set-env name=outdir::"$(cut -d' ' -f3 <<<"$commitmsg")"
        echo ::set-env name=commitmsg::$commitmsg
    - name: grab ouxml
      run: |
        ouxml_grab $url
 
    - name: convert to md
      run: |
        ouxml2md --dbname openlearn_oer.db --outdir "$outdir"
        
    - name: git add and push
      run: |
        git config --global user.email "${GH_EMAIL}"
        git config --global user.name "${GH_USERNAME}"
        git add "$outdir"
        git add openlearn_oer.db
        git commit -m"Add content to $outdir from $url" -a || true
        git push
      env: 
        GH_EMAIL: ${{ github.event.commits[0].author.email }}
        GH_USERNAME: ${{ github.event.commits[0].author.username }}
