name: OpenLearnXML
on:
  push

jobs:
  openlearn-files:
    if: startsWith(github.event.commits[0].message, 'Fetch https://www.open.edu/openlearn')
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
 
    - name: Install dependencies
      run: python -m pip install --upgrade git+https://github.com/innovationOUtside/open-ouxml-tools.git
      
    - name: Copy Repository Contents
      uses: actions/checkout@v2


    - name: get commit message
      run: |
         echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
        
    - name: handle ouxml
      run: |
        git config --global user.email "${GH_EMAIL}"
        git config --global user.name "${GH_USERNAME}"
        url="$(cut -d' ' -f2 <<<"$commitmsg")"
        outdir="$(cut -d' ' -f3 <<<"$commitmsg")"
        ouxml_grab $url
        ouxml2md --dbname openlearn_oer.db --outdir "$outdir"
        git add demo
        git commit -m"Add content from $url"
        git push
      env: 
        GH_EMAIL: ${{ github.event.commits[0].author.email }}
        GH_USERNAME: ${{ github.event.commits[0].author.username }}
